plugins {
    id 'java'
    id 'eclipse'
    id 'net.minecraftforge.gradle' version '6.+'
}

group = "dev.galacticraft"
archivesBaseName = "Galacticraft"
version = "${mod_version}${version_suffix}"

java.toolchain.languageVersion = JavaLanguageVersion.of(8)

// 👈 核心修复 1：读取 gradle.properties 里的变量，为 Forge 注入映射表配置
minecraft {
    mappings channel: project.findProperty('mapping_channel') ?: 'stable', version: project.findProperty('mapping_version') ?: '39-1.12'
}

repositories {
    mavenCentral()
    maven {
        name = "CurseMaven"
        url = "https://www.cursemaven.com"
    }
    maven {
        name 'JEI'
        url 'https://maven.blamejared.com/'
    }
    maven {
        name 'IC2'
        url 'https://maven.ic2.player.to/'
    }
    maven {
        name = "BuildCraft"
        url = "https://mod-buildcraft.com/maven"  
    }
    maven {
        name 'AE2'
        url 'https://maven.ae2dev.com/'
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${MC_VERSION}-${forge_version}"
    
    implementation "curse.maven:mekanism-268560:2835175"
    implementation "net.industrial-craft:industrialcraft-2:2.8.222-ex112:dev"
    implementation "com.mod-buildcraft.api:buildcraft-api:7.99.24.8"
    
   // compileOnly fg.deobf('mod.dependency:biomes-o-plenty:7.0.1.2445')
    implementation fg.deobf('curse.maven:applied-energistics-2-223794:2747063')
    implementation fg.deobf('curse.maven:redstoneflux-270789:2920436')
    implementation "appeng:appliedenergistics2:rv6-stable-7"
    implementation fg.deobf('curse.maven:playerapi-449521:3212872')
    compileOnly "mezz.jei:jei_${MC_VERSION}:${jei_version}:api"
    runtimeOnly "mezz.jei:jei_${MC_VERSION}:${jei_version}"
    
    // Project lombok
    compileOnly 'org.projectlombok:lombok:1.18.24'
    annotationProcessor 'org.projectlombok:lombok:1.18.24'
    testCompileOnly 'org.projectlombok:lombok:1.18.24'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.24'
}

clean {
    def filteredDelete = new HashSet<>()
    for (def toDelete : getDelete()) {
        for (def f : file(toDelete).listFiles()) {
            if (f.getName() != "fg_cache") {
                filteredDelete.add(f)
            }
        }
    }
    setDelete(filteredDelete)
}

tasks.withType(GenerateModuleMetadata).configureEach {
    enabled = false
}
