plugins {
    id 'java'
    id 'eclipse'
    id 'net.minecraftforge.gradle' version '6.+'
}

group = "dev.galacticraft"
archivesBaseName = "Galacticraft"
version = "${mod_version}${version_suffix}"

java.toolchain.languageVersion = JavaLanguageVersion.of(8)

minecraft {
    mappings channel: project.findProperty('mapping_channel') ?: 'stable', version: project.findProperty('mapping_version') ?: '39-1.12'
    accessTransformer = project.file('src/main/resources/META-INF/accesstransformer.cfg')
}

repositories {
    mavenCentral()
    maven {
        name = "BuildCraft"
        url = "https://mod-buildcraft.com/maven"
    }
    maven {
        name 'JEI'
        url 'https://maven.blamejared.com/'
    }
    maven {
        name 'IC2'
        url 'https://maven.ic2.player.to/'
    }
    maven {
        name 'AE2'
        url 'https://maven.ae2dev.com/'
    }
    maven {
        name = "CurseMaven"
        url = "https://www.cursemaven.com"
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${MC_VERSION}-${forge_version}"
    
    implementation "curse.maven:mekanism-268560:2835175"
    implementation "net.industrial-craft:industrialcraft-2:2.8.222-ex112:dev"
   // compileOnly "curse.maven:buildcraft-61811:6376391"
    implementation "curse.maven:redstoneflux-270789:2920436"
    implementation "curse.maven:appliedenergistics2-223794:2747063"
    implementation "curse.maven:playerapi-449521:3212872"
    compileOnly "mezz.jei:jei_${MC_VERSION}:${jei_version}:api"
    runtimeOnly "mezz.jei:jei_${MC_VERSION}:${jei_version}"
    
    // Project lombok
    compileOnly 'org.projectlombok:lombok:1.18.24'
    annotationProcessor 'org.projectlombok:lombok:1.18.24'
    testCompileOnly 'org.projectlombok:lombok:1.18.24'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.24'
}


processResources {
    filesMatching("mcmod.info") {
        expand(version: project.version)
    }
}

clean {
    def filteredDelete = new HashSet<>()
    for (def toDelete : getDelete()) {
        for (def f : file(toDelete).listFiles()) {
            if (f.getName() != "fg_cache") {
                filteredDelete.add(f)
            }
        }
    }
    setDelete(filteredDelete)
}

tasks.withType(GenerateModuleMetadata).configureEach {
    enabled = false
}
